const express = require("express");
const router = express.Router();
const ctrl = require("../controllers/adminController");

router.post("/addAcadEvent", ctrl.addAcadEvent);
router.post("/deleteAcadEvent/:event_ID", ctrl.deleteAcadEvent_event_ID);
router.post("/getAcademicEvent", ctrl.getAcademicEvent);
router.post("/addtasks", ctrl.addtasks);
router.post("/edittasks/:task_ID", ctrl.edittasks_task_ID);
router.post("/deletetask", ctrl.deletetask);
router.post("/deletenote", ctrl.deletenote);
router.post("/comments", ctrl.comments);
router.post("/addnote", ctrl.addnote);
router.post("/tasks/:taskID/:username", ctrl.tasks_taskID_username);
router.post("/comments/:taskID/:isComment", ctrl.comments_taskID_isComment);
router.post("/editnote/:stickyID/", ctrl.editnote_stickyID_);
router.post("/taskstatus/:taskID/:userName", ctrl.taskstatus_taskID_userName);
router.post("/users", ctrl.users);
router.post("/users/:userName", ctrl.users_userName);
router.post("/tasks/:userName", ctrl.tasks_userName);
router.post("/stickynotes/:userName", ctrl.stickynotes_userName);
router.post("/singletask/:taskID/:userName", ctrl.singletask_taskID_userName);
router.post("/guests/:task_ID", ctrl.guests_task_ID);
router.post("/noteguests", ctrl.noteguests);
router.post("/comments/:taskID", ctrl.comments_taskID);
router.post("/addEvents", ctrl.addEvents);
router.post("/getEvents", ctrl.getEvents);
router.post("/addEventsTask", ctrl.addEventsTask);
router.post("/getEventsInfoById", ctrl.getEventsInfoById);
router.post("/getEventsTaskById", ctrl.getEventsTaskById);
router.post("/UpdateEventsTask", ctrl.UpdateEventsTask);
router.post("/addDailytask", ctrl.addDailytask);
router.post("/getDailyTaskUser", ctrl.getDailyTaskUser);
router.post("/getDailyTaskAllUser", ctrl.getDailyTaskAllUser);
router.post("/getDailyTaskByDate", ctrl.getDailyTaskByDate);
router.post("/UpdateDailyTaskStatus", ctrl.UpdateDailyTaskStatus);
router.post("/addRoute", ctrl.addRoute);
router.post("/getRoute", ctrl.getRoute);
router.post("/getRouteById", ctrl.getRouteById);
router.post("/DeleteRouteById", ctrl.DeleteRouteById);
router.post("/AssignRouteEmployee", ctrl.AssignRouteEmployee);
router.post("/geAssignRouteEmployee", ctrl.geAssignRouteEmployee);
router.post("/getApproveCount", ctrl.getApproveCount);

module.exports = router;
