const express = require("express");
const router = express.Router();
const ctrl = require("../controllers/hrController");

router.post("/addRecruitmentRequest", ctrl.addRecruitmentRequest);
router.post("/changeRecruitmentRequestStatus", ctrl.changeRecruitmentRequestStatus);
router.post("/changeEvolutionQA", ctrl.changeEvolutionQA);
router.post("/changeTeacherInterviewData", ctrl.changeTeacherInterviewData);
router.post("/addRecruitmentApplicant", ctrl.addRecruitmentApplicant);
router.post("/changeRecruitmentApplicantStatus", ctrl.changeRecruitmentApplicantStatus);
router.post("/changeRecruitmentApplicantEvolutor", ctrl.changeRecruitmentApplicantEvolutor);
router.post("/changeRecruitmentApplicantFeedback", ctrl.changeRecruitmentApplicantFeedback);
router.post("/getAllRecruitmentRequest", ctrl.getAllRecruitmentRequest);
router.post("/getAllEvolutorData", ctrl.getAllEvolutorData);
router.post("/getAllRecruitmentApplicantList", ctrl.getAllRecruitmentApplicantList);
router.post("/getAllRecruitmentApplicantListByID", ctrl.getAllRecruitmentApplicantListByID);
router.post("/createLeaveRequest", ctrl.createLeaveRequest);
router.post("/changeLeaveCheckIn", ctrl.changeLeaveCheckIn);
router.post("/getApprovingAuthority", ctrl.getApprovingAuthority);
router.post("/changeLeaveApplicationStatus", ctrl.changeLeaveApplicationStatus);
router.post("/changeResignationApplicationStatus", ctrl.changeResignationApplicationStatus);
router.post("/getAllLeaveRequest", ctrl.getAllLeaveRequest);
router.post("/getAllResignRequest", ctrl.getAllResignRequest);
router.post("/getLeaveRequestByID", ctrl.getLeaveRequestByID);
router.post("/getRegisnationApprovingAuthority", ctrl.getRegisnationApprovingAuthority);
router.post("/createResignation", ctrl.createResignation);
router.post("/getResignationById", ctrl.getResignationById);
router.post("/deleteResignation", ctrl.deleteResignation);
router.post("/createClearanceForm", ctrl.createClearanceForm);
router.post("/getClearanceFormList", ctrl.getClearanceFormList);
router.post("/updateClearanceForm", ctrl.updateClearanceForm);
router.post("/uploadClearanceScanCopy", ctrl.uploadClearanceScanCopy);
router.post("/getClearanceEmployee", ctrl.getClearanceEmployee);
router.post("/addCompensationBenefits", ctrl.addCompensationBenefits);
router.post("/getCompensationBenefitsList", ctrl.getCompensationBenefitsList);
router.post("/addOtherLeave", ctrl.addOtherLeave);
router.post("/getOtherLeave", ctrl.getOtherLeave);
router.post("/getOtherLeaveById", ctrl.getOtherLeaveById);
router.post("/EditOtherLeaveById", ctrl.EditOtherLeaveById);
router.post("/DeleteOtherLeaveById", ctrl.DeleteOtherLeaveById);
router.post("/UpdateOtherLeaveById", ctrl.UpdateOtherLeaveById);
router.post("/ApprovelOtherLeaveById", ctrl.ApprovelOtherLeaveById);
router.post("/updateEmployee", ctrl.updateEmployee);
router.post("/updateEmployeeAttendancePeriod", ctrl.updateEmployeeAttendancePeriod);
router.post("/editdepartment", ctrl.editdepartment);
router.post("/deleteDept", ctrl.deleteDept);
router.post("/editdesignation", ctrl.editdesignation);
router.post("/deleteDesg", ctrl.deleteDesg);
router.post("/editEmployeeAttendancePeriod", ctrl.editEmployeeAttendancePeriod);
router.post("/deleteEmployee", ctrl.deleteEmployee);
router.post("/addExitApplicationForm", ctrl.addExitApplicationForm);
router.post("/getExitApplicationForm", ctrl.getExitApplicationForm);
router.post("/getExitApplicationFormById", ctrl.getExitApplicationFormById);
router.post("/getStudentViewByStId", ctrl.getStudentViewByStId);
router.post("/updateAmissionStudentImagesById", ctrl.updateAmissionStudentImagesById);
router.post("/updateStudentImagesById", ctrl.updateStudentImagesById);
router.post("/updateStudent", ctrl.updateStudent);
router.post("/postAttendence", ctrl.postAttendence);

module.exports = router;
