const express = require("express");
const router = express.Router();
const ctrl = require("../controllers/procurementController");

router.post("/getrequisionItemById", ctrl.getrequisionItemById);
router.post("/getrequisionItemByIdList", ctrl.getrequisionItemByIdList);
router.post("/getrequisionItemApprovelChk", ctrl.getrequisionItemApprovelChk);
router.post("/DeleteRequisionFullApproved", ctrl.DeleteRequisionFullApproved);
router.post("/DeleteRequisionApproval", ctrl.DeleteRequisionApproval);
router.post("/getrequisionFullApprovedChk", ctrl.getrequisionFullApprovedChk);
router.post("/getrequisionApprovedChk", ctrl.getrequisionApprovedChk);
router.post("/getitemsByCsRequId", ctrl.getitemsByCsRequId);
router.post("/getrequisionBycsId", ctrl.getrequisionBycsId);
router.post("/getrequisioncsByID", ctrl.getrequisioncsByID);
router.post("/submitrequisionCSRemark", ctrl.submitrequisionCSRemark);
router.post("/DeleteRequisionItemById", ctrl.DeleteRequisionItemById);
router.post("/getrequisionData", ctrl.getrequisionData);
router.post("/getrequisionCSData", ctrl.getrequisionCSData);
router.post("/getCSDataById", ctrl.getCSDataById);
router.post("/getrequisitionItemId", ctrl.getrequisitionItemId);
router.post("/requisitionItemSubmit", ctrl.requisitionItemSubmit);
router.post("/requisitionCSitemsubmit", ctrl.requisitionCSitemsubmit);
router.post("/deleteRequisitionTimeline", ctrl.deleteRequisitionTimeline);
router.post("/UpdaterequisitionCSApproveUpdate", ctrl.UpdaterequisitionCSApproveUpdate);
router.post("/UpdaterequisitionItemUpdate", ctrl.UpdaterequisitionItemUpdate);
router.post("/UpdateStoreRequisitionItemUpdate", ctrl.UpdateStoreRequisitionItemUpdate);
router.post("/csubmit", ctrl.csubmit);
router.post("/StoreSubmit", ctrl.StoreSubmit);
router.post("/removePermission", ctrl.removePermission);
router.post("/CoSubmit", ctrl.CoSubmit);
router.post("/managersubmit", ctrl.managersubmit);
router.post("/requisitionStatus", ctrl.requisitionStatus);
router.post("/requisitionApproveCHP", ctrl.requisitionApproveCHP);
router.post("/UpdaterequisitionApprovelUpdate", ctrl.UpdaterequisitionApprovelUpdate);
router.post("/requisitionSubmit", ctrl.requisitionSubmit);
router.post("/supplierSubmit", ctrl.supplierSubmit);
router.post("/getsupplier", ctrl.getsupplier);
router.post("/getsupplierByID", ctrl.getsupplierByID);
router.post("/UpdateSupplierByID", ctrl.UpdateSupplierByID);
router.post("/PoSubmit", ctrl.PoSubmit);
router.post("/UpdateApprovelPO", ctrl.UpdateApprovelPO);
router.post("/UpdateApprovelforPrincipal", ctrl.UpdateApprovelforPrincipal);
router.post("/PoItemSubmit", ctrl.PoItemSubmit);
router.post("/getpolist", ctrl.getpolist);
router.post("/getpoItemallinfo", ctrl.getpoItemallinfo);
router.post("/addFundRequest", ctrl.addFundRequest);
router.post("/getFundRequest", ctrl.getFundRequest);
router.post("/getFundRequestById", ctrl.getFundRequestById);
router.post("/UpdateFundRequestApprovel", ctrl.UpdateFundRequestApprovel);
router.post("/UpdateSPApprovel", ctrl.UpdateSPApprovel);
router.post("/UpdateFundRequest", ctrl.UpdateFundRequest);
router.post("/addSupplyPaymentItem", ctrl.addSupplyPaymentItem);
router.post("/getSupplyPaymentItem", ctrl.getSupplyPaymentItem);
router.post("/getSupplyPaymentItemById", ctrl.getSupplyPaymentItemById);
router.post("/getfundrequestInfo", ctrl.getfundrequestInfo);
router.post("/UpdateSupplyPayment", ctrl.UpdateSupplyPayment);
router.get("/procurementTest", ctrl.procurementTest);

module.exports = router;
