const express = require("express");
const router = express.Router();
const ctrl = require("../controllers/storeInventoryController");

router.post("/addProductType", ctrl.addProductType);
router.post("/getProductType", ctrl.getProductType);
router.post("/getProductTypeinduById", ctrl.getProductTypeinduById);
router.post("/getProductTypeById", ctrl.getProductTypeById);
router.post("/UpdateProductType", ctrl.UpdateProductType);
router.post("/addProduct", ctrl.addProduct);
router.post("/getProductByType", ctrl.getProductByType);
router.post("/getProduct", ctrl.getProduct);
router.post("/getProductById", ctrl.getProductById);
router.post("/UpdateProduct", ctrl.UpdateProduct);
router.post("/getProductLastID", ctrl.getProductLastID);
router.post("/getStudentProducts", ctrl.getStudentProducts);
router.post("/addTransferProduct", ctrl.addTransferProduct);
router.post("/updateTransferProduct", ctrl.updateTransferProduct);
router.post("/getTransferHistory", ctrl.getTransferHistory);
router.post("/updateTransferHistory", ctrl.updateTransferHistory);
router.post("/getLibraryItems", ctrl.getLibraryItems);
router.post("/getLibraryItemByID", ctrl.getLibraryItemByID);
router.post("/getLibraryIssuedItems", ctrl.getLibraryIssuedItems);
router.post("/addLibraryIssueItems", ctrl.addLibraryIssueItems);
router.post("/getIssueInfo", ctrl.getIssueInfo);
router.post("/getLibraryReturnItems", ctrl.getLibraryReturnItems);
router.post("/addLibraryReturnItems", ctrl.addLibraryReturnItems);
router.post("/addGRNinfo", ctrl.addGRNinfo);
router.post("/getGRNinfo", ctrl.getGRNinfo);
router.post("/getAllinfoByGRN", ctrl.getAllinfoByGRN);
router.post("/updateGRNBillstatus", ctrl.updateGRNBillstatus);
router.post("/updateGRNstatus", ctrl.updateGRNstatus);
router.post("/addGRNitem", ctrl.addGRNitem);
router.post("/addMDRinfo", ctrl.addMDRinfo);
router.post("/getMDRinfo", ctrl.getMDRinfo);
router.post("/updateMDRstatus", ctrl.updateMDRstatus);
router.post("/getAllMDRinfoByID", ctrl.getAllMDRinfoByID);
router.post("/addMDRitem", ctrl.addMDRitem);
router.post("/addCustomer", ctrl.addCustomer);
router.post("/UpdateCustomer", ctrl.UpdateCustomer);
router.post("/getCustomerByID", ctrl.getCustomerByID);
router.post("/getAllSearchCustomer", ctrl.getAllSearchCustomer);
router.post("/getAllCustomer", ctrl.getAllCustomer);
router.post("/deleteCustomer", ctrl.deleteCustomer);
router.post("/addquotation", ctrl.addquotation);
router.post("/getLastQuotationId", ctrl.getLastQuotationId);
router.post("/getallquotation", ctrl.getallquotation);
router.post("/getquotationItemById", ctrl.getquotationItemById);
router.post("/addinvoice", ctrl.addinvoice);
router.post("/getallinvoice", ctrl.getallinvoice);
router.post("/deleteinvoice", ctrl.deleteinvoice);
router.post("/addvendor", ctrl.addvendor);
router.post("/UpdateVendor", ctrl.UpdateVendor);
router.post("/getvendorID", ctrl.getvendorID);
router.post("/getAllVendor", ctrl.getAllVendor);
router.post("/deleteVendor", ctrl.deleteVendor);
router.post("/getLastPurchaseId", ctrl.getLastPurchaseId);
router.post("/addStoreProduct", ctrl.addStoreProduct);
router.post("/getLastStoreProductId", ctrl.getLastStoreProductId);
router.post("/getallStoreProduct", ctrl.getallStoreProduct);
router.post("/getallStoreProductItemlist", ctrl.getallStoreProductItemlist);
router.post("/getStoreProductItemById", ctrl.getStoreProductItemById);
router.post("/addbill", ctrl.addbill);
router.post("/getallbillinfo", ctrl.getallbillinfo);
router.post("/deletebill", ctrl.deletebill);
router.get("/", ctrl.get);

module.exports = router;
